import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import * as jQuery from 'jquery'; 
// import './js/android/cordova.js';
// import './js/js_lib/common.js';
window.$ = jQuery;
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
